apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
    service: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      service: backend
  template:
    metadata:
      labels:
        app: nginx
        service: backend
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80