apiVersion: v1
kind: Service
metadata:
  name: istio-lb
  namespace: istio-system
  labels:
    istio: istio-ingress
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    istio: istio-ingress
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: my-istio-operator
spec:
#  profile: default
  profile: empty
  components:
    ingressGateways:
      - name: istio-ingress
        enabled: true
        label:
          istio: my-istio-ingress
---
#apiVersion: install.istio.io/v1alpha1
#kind: IstioOperator
#spec:
#  components:
#    ingressGateways:
#      - name: istio-ingress
#        enabled: true
##      - name: istio-ingressgateway-staging
#        namespace: staging
#        enabled: true
---
#apiVersion: install.istio.io/v1alpha1
#kind: IstioOperator
#metadata:
#  namespace: istio-system
#  name: istio-operator
#spec:
#  profile: default
#  components:
#    ingressGateways:
#      - name: istio-ingress
#        enabled: true
#      - namespace: default
#        name: istio-ingressgateway-private
#        enabled: true
#        k8s:
#          serviceAnnotations:
#            service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "private"
#  values:
#    gateways:
#      istio-ingressgateway:
#        sds:
#          enabled: true