apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    app: helloworld
    backend: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      backend: nginx
  template:
    metadata:
      labels:
        app: helloworld
        backend: nginx
    spec:
      containers:
        - name: helloworld
          image: nginx
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
  labels:
    app: helloworld
    backend: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      backend: apache
  template:
    metadata:
      labels:
        app: helloworld
        backend: apache
    spec:
      containers:
        - name: helloworld
          image: httpd
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
