apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-mtls
  labels:
    app: helloworld
    mtls: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      mtls: "true"
  template:
    metadata:
      labels:
        app: helloworld
        mtls: "true"
    spec:
      containers:
        - name: helloworld
          image: oriolfilter/https-nginx-demo
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-nomtls
  labels:
    app: helloworld
    mtls: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      mtls: "false"
  template:
    metadata:
      labels:
        app: helloworld
        mtls: "false"
    spec:
      containers:
        - name: helloworld-nomtls
          image: oriolfilter/https-nginx-demo
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443