apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  #namespace: nginx-ingress-testing
  labels:
    environment: nginx-deployment
spec:
  selector:
    matchLabels:
      name: nginx-service
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx-service
    spec:
      containers:
        - name: nginxo
          image: nginx
          ports:
            - containerPort: 80
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservicea
  #namespace: nginx-ingress-testing
spec:
  rules:
    #- host: *
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-deployment
                port:
                  number: 80
  ingressClassName: nginx
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-myserviceb
#  namespace: nginx-ingress-testing
#spec:
#  rules:
#    - host: myserviceb.foo.org
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: myserviceb
#                port:
#                  number: 80
#  ingressClassName: nginx