#kubectl create deployment demo --image=httpd --port=80
#kubectl expose deployment demo
#
#kubectl create ingress demo-localhost --class=nginx \
#--rule="demo.localdev.me/*=demo:80"
#
#
#
## kubectl port-forward --namespace=ingress-nginx service/ingress-nginx-controller 8080:80
