apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: helloworld-destination-rule
spec:
  host: helloworld.default.svc.cluster.local
  subsets:
  - name: nginx
    labels:
      backend: nginx
  - name: apache
    labels:
      backend: apache
  - name: default

