apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 80
  selector:
    app: helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: byeworld
  labels:
    app: byeworld
    service: byeworld
  namespace: foo
spec:
  ports:
    - port: 9090
      name: http
      targetPort: 80
  selector:
    app: byeworld