#apiVersion: security.istio.io/v1beta1
#kind: PeerAuthentication
#metadata:
#  name: enable-mtls
#  namespace: default
#spec:
#  selector:
#    matchLabels:
#      app: helloworld
#      mtls: "true"
#  mtls:
#    mode: STRICT
#---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: disable-mtls
  namespace: default
spec:
  selector:
    matchLabels:
      app: helloworld
      mtls: "false"
  mtls:
    mode: DISABLE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: force-mtls
  namespace: default
spec:
  selector:
    matchLabels:
      app: helloworld
      mtls: "true"
  mtls:
    mode: STRICT
#  portLevelMtls:
#    443:
#      mode: STRICT
#---
#apiVersion: security.istio.io/v1beta1
#kind: PeerAuthentication
#metadata:
#  name: default-mtls
#  namespace: default
#spec:
#  mtls:
#    mode: DISABLE
