apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: github.com
  namespace: default
spec:
  host: github.com
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 8443
        tls:
          mode: SIMPLE